/**
 * Vercel serverless function: send a CSV report via email.
 * Uses Resend (free tier, 100 emails/day).
 *
 * Environment variable required:
 *   RESEND_API_KEY - from resend.com dashboard
 *
 * Optional environment variable:
 *   RESEND_FROM - sender address (default: onboarding@resend.dev)
 */

import { Resend } from "resend";

interface ReportBody {
  to: string;
  subject: string;
  csvContent: string;
  filename: string;
}

export default async function handler(req: Request): Promise<Response> {
  // Only accept POST
  if (req.method !== "POST") {
    return new Response(
      JSON.stringify({ ok: false, error: "Method not allowed" }),
      { status: 405, headers: { "Content-Type": "application/json" } },
    );
  }

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return new Response(
      JSON.stringify({ ok: false, error: "Email service not configured (no RESEND_API_KEY)" }),
      { status: 500, headers: { "Content-Type": "application/json" } },
    );
  }

  let body: ReportBody;
  try {
    body = await req.json();
  } catch {
    return new Response(
      JSON.stringify({ ok: false, error: "Invalid JSON body" }),
      { status: 400, headers: { "Content-Type": "application/json" } },
    );
  }

  if (!body.to || !body.subject || !body.csvContent || !body.filename) {
    return new Response(
      JSON.stringify({ ok: false, error: "Missing required fields: to, subject, csvContent, filename" }),
      { status: 400, headers: { "Content-Type": "application/json" } },
    );
  }

  const resend = new Resend(apiKey);
  const fromAddress = process.env.RESEND_FROM || "Pomponio Ranch <onboarding@resend.dev>";

  try {
    const csvBase64 = Buffer.from(body.csvContent, "utf-8").toString("base64");

    await resend.emails.send({
      from: fromAddress,
      to: body.to,
      subject: body.subject,
      text: `Report attached: ${body.filename}\n\nGenerated by Pomponio Ranch Labeling System.`,
      attachments: [
        {
          filename: body.filename,
          content: csvBase64,
        },
      ],
    });

    return new Response(
      JSON.stringify({ ok: true }),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Unknown email error";
    return new Response(
      JSON.stringify({ ok: false, error: msg }),
      { status: 500, headers: { "Content-Type": "application/json" } },
    );
  }
}
